import React, { Component } from 'react';
const MusicData = [
  {
    ID: 0,
    TacPham: 'I Wanna Destroy Myself',
    TacGia: 'Ezra Furman',
    Year: '2013',
    Type: 'Independent Music, Rock Music',
    Description:
      'This song is by Ezra Furman and appears on the album Day of the Dog (2013) - the second studio album by Chicago rock musician Ezra Furman. It was released in October 2013 by Bar/None Records. It comes after his début solo album The Year of No Returning which follow three albums with his previous backing band The Harpoons, it was recorded with his new backing band The Boyfriends, who formed in 2012 to tour The Year of No Returning.',
    imgUrl:
      'https://t2.genius.com/unsafe/220x220/https%3A%2F%2Fimages.genius.com%2F63kqomaf7yj763wwsof89h9ab.500x500x1.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/01-I_Wanna_Destroy_Myself-061013CD.mp3',
  },
  {
    ID: 1,
    TacPham: 'Stormy Weather',
    TacGia: 'Harold Arlen / Ted Koheler',
    Year: '1993',
    Type: 'Jass Music, Pop Music',
    Description:
      "'Stormy Weather' is a 1933 torch song written by Harold Arlen and Ted Koehler. Ethel Waters first sang it at The Cotton Club night club in Harlem in 1933 and recorded it that year, and in the same year it was sung in London by Elisabeth Welch and recorded by Frances Langford. Also 1933, for the first time in history the entire floor revue from Harlem's  Cotton Club went on tour, playing theatres in principal cities.",
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41nmQvEQeXL._SX373_BO1,204,203,200_.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/01_-_Stormy_Weather.mp3',
  },
  {
    ID: 2,
    TacPham: 'Me At The Museum, You In The Wintergardens',
    TacGia: 'Hollie Fullbrook',
    Year: '2014',
    Type: 'Traditional Music',
    Description:
      'This song is by Tiny Ruins and appears on the album Brightly Painted One, which was released in 2014. Guitarist Tom Healy and violinist Siobhanne Thompson performed on the album and appeared with the group on subsequent tours. Brightly Painted One was awarded Best Alternative Album at the New Zealand Music Awards in November 2014.',
    imgUrl: 'https://f4.bcbits.com/img/a3661990016_16.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/01_Me_At_The_Museum,_You_In_The_Wintergardens.mp3',
  },
  {
    ID: 3,
    TacPham: 'We Are All Stone',
    TacGia: 'Outer Minds',
    Year: '2012',
    Type: 'Rock Music',
    Description:
      "A song from Album Behind the Mirror The Chicago garage-rock band's second LP of 2012 shows a dramatic shift in tone from the bubblegum-via-psych melodies of their self-titled debut. On Behind the Mirror they aim for 'darker' psych, music that favors minor-key organ lines over bright, jangling guitar.",
    imgUrl:
      'https://media.pitchfork.com/photos/5929c0635e6ef95969323547/1:1/w_320/7c35cc18.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/06_we_are_all_stone.mp3',
  },
  {
    ID: 4,
    TacPham: 'Afria Talks To You',
    TacGia: 'Delicate Steve',
    Year: '2012',
    Type: 'Rock Music',
    Description:
      'A song from Album Positive Force, was released on Luaka Bop. The album quickly received high praise, including an 84 from Filter, an 8.5 from Paste, a 7.6 in Pitchfork and a 7 from Spin.',
    imgUrl: 'https://i1.sndcdn.com/artworks-000037022195-3jrp9e-t500x500.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/09_Afria_Talks_To_You.mp3',
  },
  {
    ID: 5,
    TacPham: 'She Might Get Shot',
    TacGia: 'Juan Wauters',
    Year: '2015',
    Type: 'Independent Music',
    Description:
      'A song from Album Who Me?- A Album features songs sung in both Spanish and English. Wauters has shared stages with artists such as Jeff Tweedy, Mac DeMarco, and Foxygen.',
    imgUrl: 'https://i1.sndcdn.com/artworks-000106189811-edoefc-t500x500.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/08_She_Might_Get_Shot.mp3',
  },
  {
    ID: 6,
    TacPham: 'Banker and a Liar',
    TacGia: 'Reigning Sound',
    Year: '2009',
    Type: 'Punk Music',
    Description:
      "A song from Album Love & Curses - A album featuring 14 songs including one cover, 'Stick Over Me', originally recorded by a '60s band called The Glass Sun (interpreted on the album as 'Stick Up For Me').",
    imgUrl: 'https://images.shazam.com/coverart/t54601925-b318282222_s400.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/14_Banker_And_A_Liar_1.mp3',
  },
  {
    ID: 7,
    TacPham: 'My Kind of Woman',
    TacGia: 'Mac DeMarco',
    Year: '2012',
    Type: 'Independent Music',
    Description:
      'A song from Album 2, is the debut full-length studio album by Canadian musician Mac DeMarco. It was recorded in June and released in October 2012 on the Captured Tracks label.',
    imgUrl: 'https://i1.sndcdn.com/artworks-000027184431-bimuo3-t500x500.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/08_MY_KIND_OF_WOMAN.mp3',
  },
  {
    ID: 8,
    TacPham: 'Runaway',
    TacGia: 'Imperial Teen',
    Year: '2012',
    Type: 'Independent Music',
    Description:
      "A song from Album Feel the Sound - the fifth studio album by the indie pop band Imperial Teen. It was released in 2012 on Merge Records. The follow-up to 2007's The Hair the TV the Baby and the Band, the album was recorded while members of the band were living variously in San Francisco, Los Angeles, and New York City.",
    imgUrl: 'https://i.ytimg.com/vi/8lBWYNcWK8k/hqdefault.jpg',
    audioUrl:
      'http://www.panacherock.com/downloads/mp3/1._Imperial_Teen_-_Runaway_.mp3',
  },
  {
    ID: 9,
    TacPham: 'Born of Light',
    TacGia: 'Gary War',
    Year: '2010',
    Type: 'Independent Music',
    Description: "A song from EP Police Warter 12",
    imgUrl:
      'https://static.stereogum.com/uploads/2010/08/Gary-War-Police-Water-608x608.jpg',
    audioUrl: 'http://www.panacherock.com/downloads/mp3/01_Born_Of_Light.mp3',
  },
  {
    ID: 10,
    TacPham: 'Thank God for Sinners',
    TacGia: 'Ty Segall',
    Year: '2012',
    Type: 'Independent Music',
    Description: "A song from Twin (Ty Segall album), the fifth studio album by San Francisco singer-songwriter Ty Segall. It marked his third and final release of the year, preceded by Slaughterhouse by the Ty Segall Band and Hair in collaboration with White Fence. Still in Rock described this LP as being 'the darkest of all Ty Segall albums'.",
    imgUrl: 'https://i.ytimg.com/vi/LRHmys84Z34/hqdefault.jpg',
    audioUrl: 'http://www.panacherock.com/downloads/mp3/01_Thank_God_for_Sinners.mp3',
  },
  {
    ID: 11,
    TacPham: 'Ropes That Way',
    TacGia: 'Dirty Ghosts',
    Year: '2012',
    Type: 'Independent Music',
    Description: "A song from Metal Moon ( Dirty Ghost Album ) - which is published by Dirty Ghosts - a San Francisco rock band formed in 2006 by Allyson Baker, Carson Binks and Baker's then-husband Aesop Rock, AKA Ian Bavitz. After the departure of Binks and Bavitz, Baker remained as the driving force in the band.",
    imgUrl: 'https://i.ytimg.com/vi/4Lu9ydAkXzY/hqdefault.jpg',
    audioUrl: 'http://www.panacherock.com/downloads/mp3/01_Ropes_That_Way_2.mp3',
  },
  {
    ID: 12,
    TacPham: 'Lament For Morning',
    TacGia: 'Raleigh Moncrief',
    Year: '2011',
    Type: 'Rock Music',
    Description: "A song from Watered Lawn Album. Al Horner of Drowned in Sound gave the album an 8 out of 10, describing it as a dizzying rush of grinding synths, sun-splashed harmonies and wide-eyed eccentricity – with a strange beauty to match its outlandishness. It was ranked at number 19 on Tiny Mix Tapes 'Favorite 25 Album Covers of 2011' list.",
    imgUrl: 'https://i.ytimg.com/vi/kg3kPZKqpZM/hqdefault.jpg',
    audioUrl: 'http://www.panacherock.com/downloads/mp3/01_lament_for_morning.mp3',
  },
  {
    ID: 13,
    TacPham: 'Movie Music Kills a Kiss',
    TacGia: 'Califone',
    Year: '2013',
    Type: 'Independent Music',
    Description: "A song from album Stiches (Califone album) by Califone, an experimental rock band from Chicago. The band is named after Califone International, an audio equipment manufacturer. Their work has been critically acclaimed.",
    imgUrl: "https://static.stereogum.com/uploads/2014/01/Califone-Movie-Music-Kills-A-Kiss-video-640x359.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/01_movie_music_kills_a_kiss.mp3",
  },
  {
    ID: 14,
    TacPham: 'Open Windows',
    TacGia: 'That Ghost ',
    Year: '2008',
    Type: 'Independent Music',
    Description: "A song from album Young Fridays, which was published by That Ghost - an artist. That Ghost has released 4 Album: Young Fridays, Songs Out Here, Get It and Get Out, Rosalind",
    imgUrl: 'https://geo-media.beatport.com/image/c1ec9566-fd4f-4a1e-b459-a58a2976cf60.jpg',
    audioUrl: 'http://www.panacherock.com/downloads/mp3/that_ghost-open_windows.mp3',
  },
  {
    ID: 15,
    TacPham: 'Henry Joe',
    TacGia: 'Billy Nayer Show',
    Year: '2010',
    Type: 'Independent Music',
    Description: "The song has been published by The Billy Nayer Show - a New York based musical group of questionable genre. The band consists of lead singer and songwriter Cory McAbee, drummer Bobby Lurie and bassist Frank Swart.",
    imgUrl: "https://i.ytimg.com/vi/EZ0KJ5uTlLk/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_billy_nayer_show-henry_joe.mp3",
  },
  {
    ID: 16,
    TacPham: 'Run to Your Grave',
    TacGia: 'The Mae Shi',
    Year: '2008',
    Type: 'Punk Music',
    Description: "The song has been pubished by The Mae Shi - an experimental rock band from Los Angeles, California, formed in 2002. The Mae Shi is also known for composing music for Nickelodeon's CG-animated series, Fanboy & Chum Chum. They first recorded the theme song for the series, followed by the promotional song, and later composed musical cues for the show in some episodes, such as Back from the Future and The Great Bicycle Mystery.",
    imgUrl: "https://i.ytimg.com/vi/PUKAcKKQns4/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_mae_shi-run_to_your_grave.mp3",
  },
  {
    ID: 17,
    TacPham: "No One's Little Girl",
    TacGia: 'The Raincoats',
    Year: '1983',
    Type: 'Rock Music',
    Description: "A song from album Moving, released by Rough Trade Records in 1983, is the third studio album by the Raincoats. It was re-released in the US by DGC Records in 1993, and in the UK by Rough Trade in 1994, with a different track list and altered cover art. On its original release, the album reached No. 5 in the UK Indie Chart.",
    imgUrl: "https://i.ytimg.com/vi/Oy89TpHO510/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_raincoats_-no_one_s_little_girl.mp3",
  },
  {
    ID: 18,
    TacPham: 'Debt and E.S.P',
    TacGia: 'The Intelligence',
    Year: '2009',
    Type: 'Independent Music',
    Description: "The song from Album Fake Surfers, released by The Intelligence, is an American rock band from Seattle, Washington, formed in 1999. Founded by multi-instrumentalist Lars Finberg (A Frames, Thee Oh Sees), the band currently consists of Finberg, alongside Dave Hernandez (guitar), Drew Church (bass) and Kaanan Tupper (drums).",
    imgUrl: "https://i.ytimg.com/vi/KemZ0IbM_3c/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_intelligence-debt_and_esp.mp3",
  },
  {
    ID: 19,
    TacPham: 'Reservoir Park',
    TacGia: 'The Dutchess and the Duke',
    Year: '2008',
    Type: 'Independent Music',
    Description: "The song from Album She's the Dutchess, He's the Duke and published by The Dutchess and the Duke, a folk band formed in Seattle, Washington, by singer-songwriters Jesse Lortz and Kimberly Morrison. Their music has been compared to the raw garage rock of the early 1960s.",
    imgUrl: "https://i.ytimg.com/vi/IyvqU9Uz9pM/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_dutchess_and_the_duke-reservoir_park.mp3",
  }, 
  {
    ID: 20,
    TacPham: 'Woven Music for Blue Steppe',
    TacGia: 'Shinji Masuko',
    Year: '2011',
    Type: 'Independent Music',
    Description: "N/A",
    imgUrl: "https://i.ytimg.com/vi/9NEJ54kAZCY/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/shinji_masuko-woven_music_for_blue_steppe.mp3",
  },
  {
    ID: 21,
    TacPham: 'Night Of The Hunter',
    TacGia: 'Tussle',
    Year: '2008',
    Type: 'Electronic Music',
    Description: "A song from Tussle Band, an American four-piece band from San Francisco, United States, formed in 2001 by Nathan Burazer, Jonathan Holland, Alexis Georgopoulos, Andy Cabic. The band released its first album, Kling Klang, in 2004 on Troubleman Unlimited.",
    imgUrl: "https://images.shazam.com/coverart/t70028244-b296644242_s400.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/tussle-night_of_the_hunter_.mp3",
  },
  {
    ID: 22,
    TacPham: 'Doing Our Part',
    TacGia: 'The Carrot',
    Year: '2008',
    Type: 'Rock Music, Pop Music',
    Description: "N/A",
    imgUrl: "https://f4.bcbits.com/img/a3950729132_16.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_carrots-doing_our_part.mp3",
  },
  {
    ID: 23,
    TacPham: 'Negative Drip',
    TacGia: 'The Terrible Twos',
    Year: '2013',
    Type: 'Rock Music',
    Description: "A song from album Horror Vacui, which was publised by The Terrible Twos, an alternative children's band from Lawrence, Kansas. They have the same line-up as The New Amsterdams.",
    imgUrl: "https://m.media-amazon.com/images/I/917YDc8RtgL._SS500_.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/terrible_twos-negative_drip.mp3",
  },
  {
    ID: 24,
    TacPham: 'Stop Stomp Stompin',
    TacGia: 'The Coathangers',
    Year: '2009',
    Type: 'Pop Punk Music',
    Description: "A song from album Scramble, published by The Coathangers, a punk rock/garage band band from Atlanta, Georgia featuring singer/guitarist Julia Kugel-Montoya (Crook Kid Coathanger), bassist Meredith Franco (Minnie Coathanger) and singer/drummer Stephanie Luke (Rusty Coathanger).",
    imgUrl: "https://f4.bcbits.com/img/a1853657014_2.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_coathangers-stop_stomp_stompin__.mp3",
  },
  {
    ID: 25,
    TacPham: 'Me And You',
    TacGia: 'The Strange Boys',
    Year: '2011',
    Type: 'Independent Music',
    Description: "A song from album Live Music, publised by The Strange Boys - were an American rock band based in Austin, Texas, composed of Ryan Sambol (guitar, lead vocals, harmonica), Philip Sambol (bass), Greg Enlow (guitar), Mike La Franchi (drums), Jenna E. Thornhill DeWitt (saxophone, backing vocals), and Tim Presley (backing vocals). Their music incorporates stylistic elements of garage rock, punk, R&B and country music.",
    imgUrl: "https://i.ytimg.com/vi/G2KRB30HVX4/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/the_strange_boys-meandyou.mp3",
  },
  {
    ID: 26,
    TacPham: 'Black Mold Grow',
    TacGia: 'Levek',
    Year: '2012',
    Type: 'Independent Music, Rock Music',
    Description: "A song from album Look a Little Closer, published by Levek band",
    imgUrl: "https://i.ytimg.com/vi/uYtbSs1QjDM/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/01_Black_Mold_Grow.mp3",
  },
  {
    ID: 27,
    TacPham: 'Imagining My Man',
    TacGia: 'Aldous Harding',
    Year: '2017',
    Type: 'Independent Music',
    Description: "A song from album Party, published by Aldous Harding, a New Zealand folk singer-songwriter. Album Party was nominated for Album of the Year at the 2017 New Zealand Music Awards. It was also nominated for IMPALA's European Album of the Year Award.",
    imgUrl: "https://www.leguesswho.nl/media/news/ALDOUS-HARDING-IMAGINING-MY-MAN.png",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_Imagining_My_Man.mp3",
  },
  {
    ID: 28,
    TacPham: 'Where Will You Go',
    TacGia: 'Evanescence',
    Year: '2000',
    Type: 'Rock Music',
    Description: "A song from album Origin, published by Evanescence - an American rock band founded in Little Rock, Arkansas, in 1995 by singer and pianist Amy Lee and guitarist Ben Moody.",
    imgUrl: "https://i.ytimg.com/vi/3WKcocEMGT8/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/01_Where_Will_You_Go.mp3",
  },
  {
    ID: 29,
    TacPham: 'Clerical Collar',
    TacGia: 'Slim Twig',
    Year: '2012',
    Type: 'Independent Music',
    Description: "A song from album A Hound At The Hem, which published by Slim Twig - a Canadian songwriter, musician and film actor. Slim Twig was born the son of Toronto-based filmmakers, Ross Turnbull and Jennifer Hazel, and graduated from the Claude Watson School of the Arts in 2006.",
    imgUrl: "https://i.ytimg.com/vi/4FvPWyY79Ek/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_Clerical_Collar_copy.mp3",
  },
  {
    ID: 30,
    TacPham: "(I've Got The) Sanctioned Blues",
    TacGia: 'Ultimate Painting',
    Year: '2015',
    Type: 'Independent Music',
    Description: "A song from album Green Lanes, published by Ultimate Painting - an English alternative rock band, formed in London in 2014. The band was composed of co-frontmen Jack Cooper and James Hoare, with a revolving cast of rhythm sections. The band were named after a painting made by the Drop City art community in Colorado in the late 1960's.",
    imgUrl: "https://i.ytimg.com/vi/8BoCAyH290s/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_(Ive_Got_The)_Sanctioned_Blues.mp3",
  },
  {
    ID: 31,
    TacPham: 'Hare Tarot Lies',
    TacGia: 'No Joy',
    Year: '2013',
    Type: 'Independent Music',
    Description: "A Song from album Wait to Pleasure, published by No Joy - a Canadian shoegaze band, formed in late 2009 by Jasamine White-Gluz and Laura Lloyd.",
    imgUrl: "https://i.ytimg.com/vi/7WYDMj_sCFg/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_Hare_Tarot_Lies.mp3",
  },
  {
    ID: 32,
    TacPham: 'Transparency Is The New Mystery',
    TacGia: 'Marnie Stern',
    Year: '2010',
    Type: 'Rock Music',
    Description: "A song from Marnie Stern (Album) published by Marnie Stern - an American musician, singer-songwriter, and guitarist. Marnie Stern has garnered acclaim for her technical skill and tapping style of guitar play. Stern is also a current member of The 8G Band from the show Late Night with Seth Meyers.",
    imgUrl: "https://i.ytimg.com/vi/hIUTxmRnf8Q/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_03_TRANSPARENCY_IS_THE_NEW_MYSTERY.mp3",
  },
  {
    ID: 33,
    TacPham: 'The Wives of Artie Shaw',
    TacGia: 'Kinski',
    Year: '2005',
    Type: 'Rock Music',
    Description: "A song from album Alpine Static, publised by Kinski. Kinski is an American rock band from Seattle, Washington. They have released eight albums, a number of split albums and EP.",
    imgUrl: "https://i.ytimg.com/vi/tk7n_e9DacM/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_The_Wives_Of_Artie_Shaw.mp3",
  },
  {
    ID: 34,
    TacPham: 'So What If We Die',
    TacGia: "OBN III's",
    Year: '2012',
    Type: 'Independent Music',
    Description: "A song from OBN III's (Album), published by OBN III's band",
    imgUrl: "https://f4.bcbits.com/img/a2321267119_10.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_So_What_If_We_Die.mp3",
  },
  {
    ID: 35,
    TacPham: 'Best Friend',
    TacGia: 'Dent May',
    Year: '2000',
    Type: 'Independent Music',
    Description: "A song from album Do Thing, published by Dent May. James Dent May Jr., known by his stage name Dent May is an American singer-songwriter based in Los Angeles, California. He is mostly associated with psychedelic pop, synthpop, indie rock, and new wave genres of music.",
    imgUrl: "https://i.ytimg.com/vi/qXS_C77rbME/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/-dentmay_-_bestfriend.mp3"
  },
  {
    ID: 36,
    TacPham: 'No Sensitive man',
    TacGia: 'Haley Bonar',
    Year: '2014',
    Type: 'Independent Music',
    Description: "A song from album last War, published by Haley Bonar. Haley McCallum (born 1983), professionally known as Haley and formerly Haley Bonar, is a Canadian-born American singer and songwriter who was raised in Rapid City, South Dakota. She has lived in Duluth and currently St. Paul, Minnesota. She plays acoustic guitar, baritone electric guitar, electric guitar, and Rhodes or Wurlitzer electric piano, either solo or with her Twin Cities-based band, including Jeremy Ylvisaker, Robert Skoro, and Jacob Hanson.",
    imgUrl: "https://i.ytimg.com/vi/d6d0qIH4Nx0/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_No_Sensitive_Man.mp3",
  },
  {
    ID: 37,
    TacPham: "Workingman's Smile",
    TacGia: 'MV & EE',
    Year: '2007',
    Type: 'Rock Music',
    Description: "A song from album Goodbye Moonface, published by MV & EE. MV & EE is a Vermont-based group of musicians focused around Matt 'MV' Valentine and his partner Erika 'EE' Elder. Matt Valentine was in the neo-psychedelic group, The Tower Recordings and has also released music under his own name and the pseudonym, Matthew Dell.",
    imgUrl: "https://i.ytimg.com/vi/zdTnPE92gFY/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_Workingmans_Smile.mp3",
  },
  {
    ID: 38,
    TacPham: 'T.V. As Eyes',
    TacGia: 'Chrome',
    Year: '1979',
    Type: 'Punk Music',
    Description: "A song from album Half Machine Lip Moves, published by Chrome. Chrome is an American rock band founded in San Francisco in 1975 by musician Damon Edge and associated with the 1970s post-punk movement. The group's coarse sound blended science-fiction themes, tape experimentation, and electronic noise with distorted acid rock guitar, bring together elements of punk, psychedelia, and industrial music.",
    imgUrl: "https://direct.rhapsody.com/imageserver/images/Alb.15608437/500x500.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/01_TV_As_Eyes_1.mp3",
  },
  {
    ID: 39,
    TacPham: 'Hollywood Teeth',
    TacGia: 'No Joy',
    Year: '2015',
    Type: 'Independent Music, Rock Music',
    Description: "A song from album More Faithful, published by No Joy. No Joy are a Canadian shoegaze band, formed in late 2009 by Jasamine White-Gluz and Laura Lloyd.",
    imgUrl: "https://f4.bcbits.com/img/a2804709002_10.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Hollywood_Teeth__12.5_.14_.mp3",
  },
  {
    ID: 40,
    TacPham: 'Intelligence',
    TacGia: 'Odonis Odonis',
    Year: '2013',
    Type: 'Independent Music',
    Description: "A song from album Better, published by Odonis Odonis. Odonis Odonis are a Canadian industrial and electronic music group from Toronto, Ontario. They are known for their 2014 album Hard Boiled Soft Boiled, which was a longlisted nominee for the 2014 Polaris Music Prize.",
    imgUrl: "https://i.ytimg.com/vi/VvV68KSbm34/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Odonis_Odonis_-_Intelligence.mp3",
  },
  {
    ID: 41,
    TacPham: "Crawling on Bruised Knees",
    TacGia: "Pharmakon",
    Year: "2013",
    Type: 'Independent Music',
    Description: "A song from album Abandon, published by Pharmakon. Pharmakon is the solo experimental music project of Margaret Chardiet, based out of New York City and formed in 2007. Pharmakon's live musical act has been described as confrontational and concise, attempting to cross the boundary between performer and audience.",
    imgUrl: "https://i.ytimg.com/vi/gFiN3RIKCew/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/04_Crawling_On_Bruised_Knees.mp3",
  },
  {
    ID: 42,
    TacPham: "Magic Hearts",
    TacGia: "Calvin Love",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album New Radar, published by Music Artist Calvin Love.",
    imgUrl: "https://i.ytimg.com/vi/z-rIAuLSrzM/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Magic_Hearts_(3).mp3",
  },
  {
    ID: 43,
    TacPham: "learning slowly",
    TacGia: "Purling Hiss",
    Year: "2014",
    Type: 'Rock Music',
    Description: "A song from album Weirdon, published by Purling Hiss. Purling Hiss is the rock music project of American multi-instrumentalist Mike Polizze. Based in Philadelphia, the project was named so because of its heavy use of distortion and white noise. Originally conceived for his own personal amusement and desire to experiment, Polizze eventually self-released Purling Hiss (2009) and began touring with a live band.",
    imgUrl: "https://media.pitchfork.com/photos/5929a940c0084474cd0c0fdb/1:1/w_320/635a11a9.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Learning_Slowly.mp3",
  },
  {
    ID: 44,
    TacPham: "Hiding Drugs in the Temple (Part 2)",
    TacGia: "Kinski",
    Year: "2005",
    Type: 'Rock Music',
    Description: "A song from album Alpine Static, published by Kinski. Kinski is an American rock band from Seattle, Washington. They have released eight albums, a number of split albums and EP.",
    imgUrl: "https://i.ytimg.com/vi/xTnttrBcnbk/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Hiding_Drugs_In_The_Temple_(Part_2).mp3",
  },
  {
    ID: 45,
    TacPham: "Balaclava Lover Boogie",
    TacGia: "Amyl and The Sniffers",
    Year: "2017",
    Type: 'Independent Music',
    Description: "A song from album Big Attraction & Giddy Up, published by Amyl and The Sniffers (band).",
    imgUrl: "https://f4.bcbits.com/img/a0471807132_10.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/04_Balaclava_Lover_Boogie.mp3",
  },
  {
    ID: 46,
    TacPham: "Oak Of Guernica",
    TacGia: "YAMANTAKA // SONIC TITAN",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from album YT//ST, published by YAMANTAKA // SONIC TITAN - a Canadian experimental music and performance art collective. YT//ST is the first studio album by Canadian experimental band Yamantaka // Sonic Titan. It was initially released independently on October 1, 2011 through Psychic Handshake and later released through Canadian label Paper Bag Records on September 11, 2012, and on American label Suicide Squeeze Records on July 16, 2013.",
    imgUrl: "https://i.ytimg.com/vi/C_JwmpCEzRU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Oak_Of_Guernica.mp3",
  },
  {
    ID: 47,
    TacPham: "Feast of the First Morning",
    TacGia: "Gap Dream",
    Year: "2012",
    Type: 'Rock Music',
    Description: "A song from album Gap Dream, published by Gap Dream band. Gap Dream is an American psychedelic synthpop band founded by Gabe Fulvimar in 2012 in Fullerton, California.",
    imgUrl: "https://t2.genius.com/unsafe/253x220/https%3A%2F%2Fimages.genius.com%2Ff99eba3348cbbecd6506e2877298e51f.792x689x1.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Feast_of_the_First_Morning.mp3",
  },
  {
    ID: 48,
    TacPham: "BODIES IN THE DUNES",
    TacGia: "POP. 1280",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album Horror, published by Pop. 1280. Pop. 1280 is a self-styled cyberpunk/industrial rock band from Brooklyn, New York City. Their name is derived from Jim Thompson’s novel of the same name.",
    imgUrl: "https://static.stereogum.com/uploads/2011/12/Pop.-1280-The-Horror-640x640.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/04_Bodies_in_the_Dunes.mp3",
  },
  {
    ID: 49,
    TacPham: "Hymn Eola (Acapella)",
    TacGia: "Tonstartssbandht",
    Year: "2011",
    Type: 'Rock Music',
    Description: "A song from album hymn, published by Tonstartssbandht music band",
    imgUrl: "https://i.ytimg.com/vi/5d4xGNp5Fgs/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/03_Hymn_Eola.mp3",
  },
  {
    ID: 50,
    TacPham: "Move and Shout",
    TacGia: "Boulevards",
    Year: "2016",
    Type: 'Electronic Music',
    Description: "A song from album Groove!, published by Artist Boulevards",
    imgUrl: "https://i1.sndcdn.com/artworks-000153847636-p3e1mk-t500x500.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/04_Move_And_Shout.mp3",
  },
  {
    ID: 51,
    TacPham: "A Star Over Pureland",
    TacGia: "YAMANTAKA // SONIC TITAN",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from album YT//ST, published by YAMANTAKA // SONIC TITAN - a Canadian experimental music and performance art collective. YT//ST is the first studio album by Canadian experimental band Yamantaka // Sonic Titan. It was initially released independently on October 1, 2011 through Psychic Handshake and later released through Canadian label Paper Bag Records on September 11, 2012, and on American label Suicide Squeeze Records on July 16, 2013.",
    imgUrl: "https://i.ytimg.com/vi/C_JwmpCEzRU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/06_A_Star_Over_Pureland.mp3",
  },
  {
    ID: 52,
    TacPham: "Cash is Money",
    TacGia: "HOMESHAKE",
    Year: "2014",
    Type: 'Independent Music',
    Description: "A song from album In The Shower, published by Homeshake. Homeshake (often stylized as HOMESHAKE) is the solo musical project of Montreal-based singer-songwriter and musician Peter Sagar.",
    imgUrl: "https://i.ytimg.com/vi/BnpoY9ZVasI/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/6-Cash_is_Money.mp3",
  },
  {
    ID: 53,
    TacPham: "This Time I Got a Reason",
    TacGia: "Fuzz",
    Year: "2013",
    Type: 'Independent Music',
    Description: "A song from album Live in San Francisco, published by Fuzz. Fuzz is an American rock band from San Francisco, California, formed in 2011. The band consists of Charles Moothart (vocals, guitar), Ty Segall (vocals, drums) and Chad Ubovich (vocals, bass).",
    imgUrl: "https://i.ytimg.com/vi/Ist-fcXsU1g/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/A_-_This_Time_I_Got_A_Reason.mp3",
  },
  {
    ID: 54,
    TacPham: "Like it Was Again",
    TacGia: "Dignan Porch",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A sing from album Deluded, published by Dignan Porch. Dignan Porch is a DIY indie rock band from Tooting Broadway, London. They began as the bedroom recording project of songwriter Joseph Walsh, then grew into a full band, creating music that has been described by critics as a combination of Lo-fi, indie rock, pop and punk.",
    imgUrl: "https://i.ytimg.com/vi/iAWSuUyvB0g/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/3._Like_it_was_again_-_.mp3",
  },
  {
    ID: 55,
    TacPham: "Optimist High",
    TacGia: "Chris Cohen",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album from Overgrown Path, published by Chris Cohen. Chris Cohen is an American multi-instrumentalist, singer-songwriter and producer best known for his solo albums as well as for having been a member of the band Deerhoof between 2002 and 2006.",
    imgUrl: "https://media.pitchfork.com/photos/5929bff05e6ef9596932349f/1:1/w_320/e6119fa4.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/06_Optimist_High.mp3",
  },
  {
    ID: 56,
    TacPham: "This is The Last Time I Shake your Hand",
    TacGia: "TSOWC",
    Year: "2010",
    Type: 'Electronic Music',
    Description: "A song from album The Suicide of Western Culture, published by TSOWC (The Suicide of Western Culture) band.",
    imgUrl: "https://m.media-amazon.com/images/I/71nGwl4ykWL._SS500_.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/1.-THE_SUICIDE_OF_WESTERN_CULTURE_THIS_IS_THE_LAST_TIME_I_SHAKE_YOUR_HAND_.mp3",
  },
  {
    ID: 57,
    TacPham: "Horror Stories for Whores",
    TacGia: "Dante Vs Zombies",
    Year: "2012",
    Type: 'Rock Music',
    Description: "A song fom album Buh, published by Dante Vs Zombies band.",
    imgUrl: "https://i.ytimg.com/vi/hD6mSw3UAXI/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Horror_Stories_For_Whores.mp3",
  },
  {
    ID: 58,
    TacPham: "Anything I Do Is All Right",
    TacGia: "Happyness",
    Year: "2014",
    Type: 'Rock Music',
    Description: "A song from album Weird Little Birthday, published by Happyness. Happyness are an alternative rock band based in London, consisting of Jon EE Allan (guitar / bass / vocals) and Ash Kenazi (drums). Their debut album Weird Little Birthday was released on 16th June 2014, later to be re-released in 2015 by Moshi Moshi Records in the UK / Bar/None Records in the USA.",
    imgUrl: "https://m.media-amazon.com/images/I/714jQET-QmL._SS500_.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Anything_I_Do_Is_All_Right.mp3",
  },
  {
    ID: 59,
    TacPham: "Crystal Fortress Over The Sea Of Trees",
    TacGia: "YAMANTAKA // SONIC TITAN",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from album YT//ST, published by YAMANTAKA // SONIC TITAN - a Canadian experimental music and performance art collective. YT//ST is the first studio album by Canadian experimental band Yamantaka // Sonic Titan. It was initially released independently on October 1, 2011 through Psychic Handshake and later released through Canadian label Paper Bag Records on September 11, 2012, and on American label Suicide Squeeze Records on July 16, 2013.",
    imgUrl: "https://i.ytimg.com/vi/C_JwmpCEzRU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Crystal_Fortress_Over_The_Sea_Of.mp3",
  },
  {
    ID: 60,
    TacPham: "Maintain The Charade",
    TacGia: "Slim Twig",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album A Hound At The Hem, which published by Slim Twig - a Canadian songwriter, musician and film actor. Slim Twig was born the son of Toronto-based filmmakers, Ross Turnbull and Jennifer Hazel, and graduated from the Claude Watson School of the Arts in 2006.",
    imgUrl: "https://i.ytimg.com/vi/YgxlXC2psTs/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Maintain_The_Charade_copy.mp3",
  },
  {
    ID: 61,
    TacPham: "Passing Out Pieces",
    TacGia: "Mac DeMarco",
    Year: "2014",
    Type: 'Independent Music',
    Description: "A song from album Salad Day, published by Mac DeMarco. Salad Days is the second full-length studio album by Canadian musician Mac DeMarco released on April 1, 2014 through Captured Tracks -  an American, Brooklyn-based independent record label.",
    imgUrl: "https://i.ytimg.com/vi/ztGGxKxnxIU/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Passing_Out_Pieces.mp3",
  },
  {
    ID: 62,
    TacPham: "Dust In The Sky",
    TacGia: "EZTV",
    Year: "2015",
    Type: 'Independent Music',
    Description: "A song from album Calling Out, published by EZTV band",
    imgUrl: "https://i.ytimg.com/vi/NGepGoQxpqc/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/B1_Dust_In_The_Sky_V1.mp3",
  },
  {
    ID: 63,
    TacPham: "Fruits of Disillusion",
    TacGia: "Yves Jarvis",
    Year: "2019",
    Type: 'Independent Music',
    Description: "A song from album The Same But By Different Means, published by Yves Jarvis",
    imgUrl: "https://i.ytimg.com/vi/qqhTZHrYWaM/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/12_-_fruits_of_disillusion.mp3",
  },
  {
    ID: 64,
    TacPham: "Shout It In",
    TacGia: "Dirty Ghosts",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from Metal Moon ( Dirty Ghost Album ), published by Dirty Ghosts - a San Francisco rock band formed in 2006 by Allyson Baker, Carson Binks and Baker's then-husband Aesop Rock, AKA Ian Bavitz. After the departure of Binks and Bavitz, Baker remained as the driving force in the band.",
    imgUrl: "https://i.ytimg.com/vi/RV9NUhVIUeE/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/dirty_ghosts-shout_it_in.mp3",
  },
  {
    ID: 65,
    TacPham: "Just Another Beautiful Boy",
    TacGia: "Carletta Sue Kay",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album Incongruent, published by musician Carletta Sue Kay",
    imgUrl: "https://i.ytimg.com/vi/-YiSSYLQEbI/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/carletta_sue_kay-beautiful_boy.mp3",
  },
  {
    ID: 66,
    TacPham: "Golden Dream",
    TacGia: "Stonefield",
    Year: "2015",
    Type: 'Electronic Music',
    Description: "A song published by Stonefield. Stonefield are an Australian rock band comprising the four Findlay sisters: Amy on drums and lead vocals, Hannah on lead guitar, Sarah on keyboards, and Holly on bass guitar. They were formed in 2006 as Iotah in Darraweit Guim, a small town in rural Victoria. They changed their name to Stonefield in 2010",
    imgUrl: "https://i.ytimg.com/vi/qUneaeh1oDE/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Golden_Dream_-_Stonefield.mp3",
  },
  {
    ID: 67,
    TacPham: "Haunted Water",
    TacGia: "SPELLING",
    Year: "2019",
    Type: 'Electronic Music',
    Description: "A song from album Mazy Fly, published by Musician SPELLING",
    imgUrl: "https://i.ytimg.com/vi/FTmBdT12qNU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/02_Haunted_Water.mp3",
  },
  {
    ID: 68,
    TacPham: "Reverse Crystal // Murder Of A Spider",
    TacGia: "YAMANTAKA // SONIC TITAN",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from album YT//ST, published by YAMANTAKA // SONIC TITAN - a Canadian experimental music and performance art collective. YT//ST is the first studio album by Canadian experimental band Yamantaka // Sonic Titan. It was initially released independently on October 1, 2011 through Psychic Handshake and later released through Canadian label Paper Bag Records on September 11, 2012, and on American label Suicide Squeeze Records on July 16, 2013.",
    imgUrl: "https://i.ytimg.com/vi/C_JwmpCEzRU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/04_Reverse_Crystal_Murder_Of_A_Spide.mp3",
  },
  {
    ID: 69,
    TacPham: "Priest Poet Pig",
    TacGia: "VietNam",
    Year: "2017",
    Type: 'Rock Music',
    Description: "A Song from album VietNam. VietNam is the full-length debut of VietNam band, released in January 2007. Mickey Madden and Jesse Carmichael of Maroon 5 helped record this album, with Madden serving as one of the executive producers. Jenny Lewis from Rilo Kiley also makes an appearance on the album.",
    imgUrl: "https://i.ytimg.com/vi/NSRfXep09fU/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/07_Priest_Poet_Pig.mp3",
  },
  {
    ID: 70,
    TacPham: "Traitor",
    TacGia: "Richard Buckner",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from Our Blood (album). Our Blood is a studio album by country musician Richard Buckner. It was released in August 2011 under Merge Records.",
    imgUrl: "https://i.ytimg.com/vi/qJgU-tAaYuI/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/1._Richard_Buckner_-_Traitor_.mp3",
  },
  {
    ID: 71,
    TacPham: "Electric Glitter Boogie",
    TacGia: "POWER",
    Year: "2015",
    Type: 'Independent Music',
    Description: "A song from Electric Glitter Boogie (album), published by POWER Music band.",
    imgUrl: "https://i.ytimg.com/vi/SKiCciDO-us/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/1_Electric_Glitter_Boogie.mp3",
  },
  {
    ID: 72,
    TacPham: "Mountain",
    TacGia: "Chad & The Meatbodies - Mountain",
    Year: "N/A",
    Type: 'N/A',
    Description: "N/A",
    imgUrl: "https://i.ytimg.com/vi/2fuiwuuq7NA/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/CHAD_AND_THE_MEATBODIES_-_7_inch_MOUNTAIN.mp3",
  },
  {
    ID: 73,
    TacPham: "Skeng",
    TacGia: "The Bug (Kevin Martin)",
    Year: "2008",
    Type: 'Electronic Music, Dubstep Music',
    Description: "A Song from album London Zoo. London Zoo is the third album by English musician Kevin Martin under his alias The Bug. It was released on 7 July 2008 by Ninja Tune Records to widespread critical acclaim. The Wire named London Zoo the record of the year in its annual critics' poll.",
    imgUrl: "https://i.ytimg.com/vi/T9mRbZPuNCE/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Bug_-_Skeng_ft_Killa_P_Flowdan.mp3",
  },
  {
    ID: 74,
    TacPham: "Daisy, where did you go?",
    TacGia: "Marissa Nadler",
    Year: "2011",
    Type: 'Traditional Music',
    Description: "A song from album Marissa Nadler. Marissa Nadler (album) is Marissa Nadler's eponymous fifth full-length studio album. It was released on June 14, 2011 by Box of Cedar Records.",
    imgUrl: "https://i.ytimg.com/vi/nK1kId5a8Y0/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Daisy,_Where_Did_You_Go_.mp3",
  },
  {
    ID: 75,
    TacPham: "Drone on (feat. jamie krasner)",
    TacGia: "Physical therapy",
    Year: "2012",
    Type: 'N/A',
    Description: "N/A",
    imgUrl: "https://www.interviewmagazine.com/wp-content/uploads/2012/08/img-drone-on-physical-therapy-_103646147273.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Drone_On_(ft._Jamie_Krasner)_.mp3",
  },
  {
    ID: 76,
    TacPham: "Black Magic Punks",
    TacGia: "Coliseum",
    Year: "2013",
    Type: 'Independent Music',
    Description: "A song from album Sister Faith, published by Coliseum. Coliseum is an American punk rock band from Louisville, Kentucky, formed in 2003. They have released 5 studio albums, most recently Anxiety's Kiss on Deathwish Inc.",
    imgUrl: "https://i.ytimg.com/vi/KnZ8dOHPpfU/sddefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Coliseum_Black_Magic_Punks.mp3",
  },
  {
    ID: 77,
    TacPham: "Call to Be",
    TacGia: "Dana Buoy",
    Year: "2012",
    Type: 'Electronic Music',
    Description: "A song from album Summer Bodies, published by Dana Buoy",
    imgUrl: "https://i.ytimg.com/vi/EBfS7r0PMYY/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/DanaBuoy-CallToBe.mp3",
  },
  {
    ID: 78,
    TacPham: "Draggin' Feet",
    TacGia: "Heaters",
    Year: "2014",
    Type: 'Independent Music',
    Description: "A song from album EP which published by Heaters. Heaters is an American alternative rock band, formed in 2013 in Grand Rapids, Michigan. The band is currently composed of singer-bassist Nolan Krebs, drummer Joshua Korf, guitarist Ryan Hagan and singer-guitarist Ben Taber. The band's original co-frontman and guitarist Andrew Tamlyn left the band in March 2017 to focus on his new band Fyrrh.",
    imgUrl: "https://i.ytimg.com/vi/ymmu2V9eccQ/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Heaters_-_EP_-_01_Draggin_Feet.mp3",
  },
  {
    ID: 79,
    TacPham: "Shank Raids",
    TacGia: "Rhyton",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from Rhyton (album), published by Rhyton - an American experimental psychedelic rock band from Brooklyn, New York.",
    imgUrl: "https://direct.rhapsody.com/imageserver/images/Alb.190585849/500x500.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Rhyton-Shank_Raids.mp3",
  },
  {
    ID: 80,
    TacPham: "New Obsession",
    TacGia: "Odonis Odonis",
    Year: "2014",
    Type: 'Independent Music, Rock Music',
    Description: "A song from album Hard Boiled Soft Boiled, published by Odonis Odonis. Odonis Odonis are a Canadian industrial and electronic music group from Toronto, Ontario. They are known for their 2014 album Hard Boiled Soft Boiled, which was a longlisted nominee for the 2014 Polaris Music Prize.",
    imgUrl: "https://i.ytimg.com/vi/v5OxBHGepZU/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Odonis_Odonis_-_New_Obsession.mp3",
  },
  {
    ID: 81,
    TacPham: "Open Your Heart",
    TacGia: "The Men",
    Year: "2011",
    Type: 'Independent Music',
    Description: "A song from album Open Your Heart. Open Your Heart is the third studio album by the Brooklyn punk rock band The Men, released March 6, 2012 on Sacred Bones Records. The album saw a change in sound for The Men, being less aggressive than the band's previous album Leave Home and incorporating influences from classic rock, country music and surf rock. The album received mostly positive reviews.",
    imgUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/TheMen_OpenYourHeart.jpg/220px-TheMen_OpenYourHeart.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/The_Men_-_Open_Your_Heart.mp3",
  },
  {
    ID: 82,
    TacPham: "Tied-Up In Paper",
    TacGia: "AIDS Wolf",
    Year: "2008",
    Type: 'Rock Music',
    Description: "A song from album Cities of Glass, published by AIDS Wolf - a Canadian noise rock band, who debuted on Pasalymany tapes but moved to Skin Graft Records and Lovepump United. The band received critical attention for their albums The Lovvers LP and Cities of Glass.",
    imgUrl: "https://i.ytimg.com/vi/HxLDhJvzWkg/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/aids_wolf-tied_up_in_paper.mp3",
  },
  {
    ID: 83,
    TacPham: "What Happens When You Turn The Devil Down?",
    TacGia: "The Mystery Lights",
    Year: "2016",
    Type: 'Rock Music',
    Description: "A song from album Mystery Light, published by The Mystery Light music band",
    imgUrl: "https://i.ytimg.com/vi/11jnyA5aSfs/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/The_Mystery_Lights_-_What_Happens_When_You_Turn_The_Devil_Down.mp3",
  },
  {
    ID: 84,
    TacPham: "The Ceiling",
    TacGia: "Thee Oh Sees",
    Year: "2015",
    Type: 'Rock Music',
    Description: "A song from album 50 Bands & A Cat for Indiana Equality, published by Thee Oh Sees - American rock band from San Francisco, California, USA, active since 1997",
    imgUrl: "https://i.ytimg.com/vi/VMYvq1HbHZg/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Thee_Oh_Sees_-_The_Ceiling.mp3",
  },
  {
    ID: 85,
    TacPham: "Silver Spring",
    TacGia: "Speedy Ortiz",
    Year: "2012",
    Type: 'Independent Music',
    Description: "A song from album Sports, published by Speedy Ortiz - an American indie rock band from Northampton, Massachusetts, United States.",
    imgUrl: "https://f4.bcbits.com/img/a0700089493_10.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Speedy_Ortiz_-_Silver_Spring.mp3",
  },
  {
    ID: 86,
    TacPham: "When You Tell Me How It Is",
    TacGia: "Richard Buckner",
    Year: "2013",
    Type: 'Independent Music, Country Music',
    Description: "A song from Surrounded (album). Surrounded is a studio album by country musician Richard Buckner. It was released in September 2013 under Merge Records.",
    imgUrl: "https://i.ytimg.com/vi/g-xl1K7TgRA/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/RichardBuckner_02v1_WhenYouTellMeHowItIs.mp3",
  },
  {
    ID: 87,
    TacPham: "Fiji Inn Hearts",
    TacGia: "Azeda Booth",
    Year: "2009",
    Type: 'N/A',
    Description: "A song from album Tubtrek, published by Azeda Booth - a Canadian experimental-pop band formed in Calgary in 2004, influenced by glitch, IDM, and experimental music.",
    imgUrl: "https://i.ytimg.com/vi/kd7CjlTJNDE/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/azeda_booth-fiji_inn_hearts.mp3",
  },
  {
    ID: 88,
    TacPham: "Shadows Moving on the Wall",
    TacGia: "Belaire",
    Year: "2007",
    Type: 'Pop Music',
    Description: "A song from album Exploding Impacting, published by Belaire music band.",
    imgUrl: "https://images.shazam.com/coverart/t45960829-b260138585_s400.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/belaire-shadows_moving_on_the_wall.mp3",
  },
  {
    ID: 89,
    TacPham: "Whatchu Want From Me",
    TacGia: "Homeboy Sandman",
    Year: "2012",
    Type: 'Rap Music',
    Description: "A song from album First of a Living Breed. First of a Living Breed is the fourth studio album by American rapper Homeboy Sandman. It was released through Stones Throw Records on September 18, 2012.",
    imgUrl: "https://i.ytimg.com/vi/jPYDGNEYr1k/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/Whatchu_Want_From_Me_(Clean_Edit).mp3",
  },
  {
    ID: 90,
    TacPham: "Trash Talk",
    TacGia: "Chain and the Gang",
    Year: "2009",
    Type: 'Independent Music',
    Description: "A song from album Down With Liberty… Up With Chains!, published by Trash Talk music band",
    imgUrl: "https://i.ytimg.com/vi/CK31oQTJBzU/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/chain_and_the_gang-trash_talk.mp3",
  },
  {
    ID: 91,
    TacPham: "Think of You",
    TacGia: "Bleached",
    Year: "2001",
    Type: 'Independent Music',
    Description: "A song published by Bleached. Bleached are an American punk rock and pop punk band consisting of sisters Jennifer Clavin and Jessica Clavin, formerly of Mika Miko. The band plays a style of punk rock, pop punk, garage rock, garage punk, rock and roll, noise pop and indie rock. Bleached was established in Los Angeles, California in 2011.",
    imgUrl: "https://i.ytimg.com/vi/--PGy31IeI4/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/bleached-think_of_you.mp3",
  },
  {
    ID: 92,
    TacPham: "Evil Twin",
    TacGia: "City Light",
    Year: "2008",
    Type: 'Rock Music',
    Description: "A song from album Down the Pacific, published by musician City Light.",
    imgUrl: "https://i.ytimg.com/vi/Ax399jot8V4/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/city_light-evil_twin.mp3",
  },
  {
    ID: 93,
    TacPham: "Tiger",
    TacGia: "Cheeseburger",
    Year: "2007",
    Type: 'Rock Music',
    Description: "A song from album Cheeseburger, published by Cheeseburger (band). Cheeseburger is an American hard rock band. They are perhaps best known for their song Comin' Home, which was used as the theme song for the Adult Swim animated television series Superjail!, which was co-created by the band's guitarist, Christy Karacas, who is also known for creating Ballmastrz: 9009.",
    imgUrl: "https://i.ytimg.com/vi/rMUEfdo5Wac/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/cheeseburger-tiger.mp3",
  },
  {
    ID: 94,
    TacPham: "Shake Your Ass",
    TacGia: "Blowfly",
    Year: "1997",
    Type: 'Soul Music, Rap Music',
    Description: "A song from album Disco, published by Blowfly (Clarence Henry Reid) - an American musician, songwriter and producer.",
    imgUrl: "https://i.ytimg.com/vi/1KmbaFkaL9g/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/blowfly-shake_your_ass.mp3",
  },
  {
    ID: 95,
    TacPham: "Dream Off",
    TacGia: "Best Fwends",
    Year: "2007",
    Type: 'N/A',
    Description: "A song from album Alphabetically Arranged, published by Best Fwends. Best Fwends are a musical group from Fort Worth, Texas.[1] All but unknown in the United States, the duo have attracted much more notice in Europe, having been featured in a Bacardi commercial in the United Kingdom and performing at Iceland Airwaves in Reykjavík and Øyafestivalen in Norway.",
    imgUrl: "https://f4.bcbits.com/img/a2287086608_5.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/best_fwends-dream_off.mp3",
  },
  {
    ID: 96,
    TacPham: "Thundermouth",
    TacGia: "Beans",
    Year: "2008",
    Type: 'Rap Music',
    Description: "A song from album Thorns - a 2008 studio album by American rapper Beans, released on Adored and Exploited. It includes contributions from Dabrye and Holy Fuck.",
    imgUrl: "https://i.ytimg.com/vi/bQUGF06DXz8/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/beans-thundermouth.mp3",
  },
  {
    ID: 97,
    TacPham: "The Motion Makes Me Last",
    TacGia: "Eluvium",
    Year: "2010",
    Type: 'Background Music',
    Description: "A song from album Similes. Similes is the fifth album from Portland, Oregon ambient musician Matthew Cooper, under the name Eluvium. The album features Cooper's first vocal performances and percussion, and is the first album to have a verse-chorus form in some of its tracks. The front cover is an artwork created by his wife, Jeannie Paske, who painted artworks for most of his other albums.",
    imgUrl: "https://i.ebayimg.com/images/g/fkAAAOSwQXBatjVg/s-l300.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/eluvium-the-motion-makes-me-last.mp3",
  },
  {
    ID: 98,
    TacPham: "Oh You Horny Monster",
    TacGia: "Fiasco",
    Year: "2008",
    Type: 'Rock Music',
    Description: "A song from album Native Canadians - the second album published by the band Fiasco.",
    imgUrl: "https://i.ytimg.com/vi/sAQa5PEyrBE/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/fiasco-oh,_you_horny_monster.mp3",
  },
  {
    ID: 99,
    TacPham: "How Can You Work?",
    TacGia: "Daniel Francis Doyle",
    Year: "2009",
    Type: 'N/A',
    Description: "A song from album We Bet Our Money on You, published by musician Daniel Francis Doyle.",
    imgUrl: "https://i.ytimg.com/vi/NqD1rGDkU98/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/daniel_francis_doyle-how_can_you_work.mp3",
  },
  {
    ID: 100,
    TacPham: "...And Now Emerges the Silver Penguin",
    TacGia: "An Albatross",
    Year: "2008",
    Type: 'Rock Music',
    Description: "A song from The An Albatross Family Album, published by An Albatross - a noise rock band based in Philadelphia, PA, known for their chaotic live shows and psychedelic/circus-like presentation.",
    imgUrl: "https://i.ytimg.com/vi/rIgXCi2k8vI/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/an_albatross-and_now_emerges_the_silver_pilgrim_.mp3",
  },
  {
    ID: 101,
    TacPham: "Damn That Valley",
    TacGia: "U.S. Girls",
    Year: "2015",
    Type: 'Independent Music',
    Description: "A song from album Half Free. Half Free is an album by U.S. Girls, the solo project of Toronto-based American musician Meghan Remy. It was released on September 25, 2015 through 4AD record label. Inspired by Sebastian Junger’s memoir War and described by its press release as 'an honest and lyrically jarring exploration of emotions, drenched in a bath of raw beats and loops' the album features contributions from Remy's husband Slim Twig, producer Onakabazien, Ben Cook of Fucked Up, Amanda Crist of Ice Cream and Tony Price.",
    imgUrl: "https://i.ytimg.com/vi/93yOrb04Eao/maxresdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/U.S_._GIRLS_-_DAMN_THAT_VALLEY_DM1_(2)_.mp3",
  },
  {
    ID: 102,
    TacPham: "Climb the Highest Mountain",
    TacGia: "Gods and Monsters",
    Year: "2011",
    Type: 'Rock Music',
    Description: "A song from album The Ordeal Of Civility, published by Gods and Monsters - an American psychedelic rock band from New York City, known for once having singer-songwriter Jeff Buckley as a member in the early 1990s.",
    imgUrl: "https://i.ytimg.com/vi/FzywiLkW6Uc/hqdefault.jpg",
    audioUrl: "http://www.panacherock.com/downloads/mp3/gods_and_monsters-climb_the_highest_mountain.mp3",
  },
  
];
export default MusicData;
